# Generated by Django 5.0.4 on 2024-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceapp', '0002_rename_place_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(default='Not specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='qualification',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
